version: "3"
services:
  ricw:
    build:
      context: raw-info-consumer-web/
    volumes:
      - /d/my_doc/mymus_db:/mymus_db
    networks:
      musorg-bridge:
        ipv4_address: 10.5.0.7
    ports:
      - 8083:8080


networks:
  musorg-bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
