version: "3"
services:
  rtic:
    build:
      context: raw-track-info-consumer/
    volumes:
      - ./local/sqlite_db:/sqlite_db
    networks:
      musorg-bridge:
        ipv4_address: 10.5.0.5

  rtiwh:
    build:
      context: raw-track-info-web-helper/
    volumes:
      - ./local/sqlite_db:/sqlite_db
    networks:
      musorg-bridge:
        ipv4_address: 10.5.0.6
    environment:
      - TIC_ADDRESS=10.5.0.5
    ports:
      - 8082:8080

  dip:
    build:
      context: deezer-info-parser/
    volumes:
      - ./local/sqlite_db:/sqlite_db
    networks:
      musorg-bridge:
        ipv4_address: 10.5.0.8
    ports:
      - 8084:8080

networks:
  musorg-bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
